title: <p align="center"> Rashmi Jennefer </p>
logo: /assets/img/profile_pic.png
description: I'm working on Data Science, Machine learning & NLP related problems.
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
